import { PrismaClient } from "@prisma/client";

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is not set.");
}

const globalForPrisma = globalThis as unknown as {
  prisma?: PrismaClient;
};

let prismaInstance: PrismaClient;

try {
  prismaInstance =
    globalForPrisma.prisma ??
    new PrismaClient({
      log:
        process.env.NODE_ENV === "development" ? ["error", "warn"] : ["error"],
      datasources: {
        db: {
          url: databaseUrl,
        },
      },
    });

  // Cache Prisma client globally to avoid multiple instances in serverless environments
  if (!globalForPrisma.prisma) {
    globalForPrisma.prisma = prismaInstance;
  }
} catch (error: any) {
  console.error("[PRISMA] Failed to initialize Prisma client:", error);
  throw new Error(
    `Failed to initialize Prisma client: ${
      error?.message || "Unknown error"
    }. ` +
      "Make sure Prisma client is generated by running: npx prisma generate"
  );
}

export const prisma = prismaInstance;
